<?php

// file generated by plugin translationbrowser, Author: Mariusz Bulkowski 

$polish = array( 
   'friendrequest'  =>  "Zaproszenie" , 
    'friendrequest:approve'  =>  "Przyjmij zaproszenie" ,
	'friendrequest:deny'  =>  "Odrzuć zaproszenie" ,
	'friendrequest:cancel' => "Anuluj zaproszenie",
   'friendrequests'  =>  "Zaproszenia" , 
   'friendrequests:title'  =>  "Zaproszenia %s" , 
   'newfriendrequests'  =>  "Nowe zaproszenie!" , 
   'friendrequest:add:exists'  =>  "Użytkownik %s jeszcze nie odpowiedział na Twoje poprzednie zaproszenie." , 
   'friendrequest:add:failure'  =>  "Przepraszamy, z powodu błędu systemu nie byliśmy w stanie obsłużyć zaproszenia. Proszę spróbuj ponownie." , 
   'friendrequest:add:successful'  =>  "Wysłano zaproszenie. %s musi je zaakceptować zanim dołączy do Twojej listy znajomych." , 
   'friendrequest:newfriend:subject'  =>  "%s zaprasza cię do grona znajomych" ,
   'friendrequest:newfriend:body'  =>  "%s zaprasza Cię do grona znajomych.

Tutaj możesz zobaczyć swoje zaproszenia:

	%s

(Nie odpowiadaj na ten e-mail, został wygenerowany automatycznie.)" , 
   'friendrequest:successful'  =>  "Dołączyłeś do grona znajomych użytkownika %s!" ,
   'friendrequest:remove:success'  =>  "Zaproszenie usunięte pomyślnie." , 
   'friendrequest:remove:fail'  =>  "Nie udało się usunąć zaproszenia." , 
   'friendrequest:approvefail'  =>  "Nieznany błąd podczas dodawania %s do listy znajomych."
);


add_translation("pl",$polish);



?>